export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const UPDATE_MOVIE_MODAL = 'UPDATE_MOVIE_MODAL';
export const ADD_TO_MOVIE_LIST = 'ADD_TO_MOVIE_LIST';
export const REMOVE_FROM_MOVIE_LIST = 'REMOVE_FROM_MOVIE_LIST';
export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const UPDATE_STAR_RATING = 'UPDATE_STAR_RATING';
export const UPDATE_WATCHED = 'UPDATE_WATCHED';
export const CLEAR_STATE = 'CLEAR_STATE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
